Rails.application.routes.draw do
  get "stations/new" => "stations#new"
  get "stations/:id" => "stations#show"
  get "stations/:id/edit" => "stations#edit"
  post "stations" => "stations#create"
  post "stations/:id/update" => "stations#update"
  post "stations/:id/pwr_cont" => "stations#pwr_cont"
  post "stations/:id/pwr_off" => "stations#pwr_off"
  post "stations/:id/btns" => "stations#btns" ,as: :stations_show
  post "stations/:id/change_power" => "stations#change_power"
  post "stations/:id/back_16" => "stations#back_16"
  post "stations/:id/menu" => "stations#menu"
  post "stations/:id/cancel" => "stations#cancel"
  post "stations/:id/break" => "stations#break"
  post "stations/:id/off_btn" => "stations#off_btn"
  post "stations/:id/func" => "stations#func"
  post "stations/:id/dsc_rtn" => "stations#dsc_rtn"
  post "stations/:id/safety_call_all_ships" => "stations#safety_call_all_ships"
  post "stations/:id/safety_call_specific_station" => "stations#safety_call_specific_station"
  post "stations/:id/urgency_call_all_ships" => "stations#urgency_call_all_ships"
  post "stations/:id/urgency_call_specific_station" => "stations#urgency_call_specific_station"
  post "stations/:id/distress_call" => "stations#distress_call"
  post "stations/:id/proxy_distress_call_all_ships" => "stations#proxy_distress_call_all_ships"
  post "stations/:id/dsc_test_call" => "stations#dsc_test_call"
  post "stations/:id/other_ships_list" => "stations#other_ships_list"
  post "stations/:id/ais_call" => "stations#ais_call"
  post "stations/:id/self_diagnosis" => "stations#self_diagnosis"
  delete "stations/:id" => "stations#destroy"

  post "dscs/ship_station_call" => "dscs#ship_station_call"
  post "dscs/safety_call_all_ships" => "dscs#safety_call_all_ships"
  post "dscs/safety_call_specific_station" => "dscs#safety_call_specific_station"
  post "dscs/urgency_call_all_ships" => "dscs#urgency_call_all_ships"
  post "dscs/urgency_call_specific_station" => "dscs#urgency_call_specific_station"
  post "dscs/distress_call" => "dscs#distress_call"
  post "dscs/proxy_distress_call_all_ships" => "dscs#proxy_distress_call_all_ships"
  post "dscs/new_call" => "dscs#new_call"
  post "dscs/:id/" => "dscs#show"
  post "dscs/:id/received_call" => "dscs#received_call"
  post "dscs/:id/new_ch" => "dscs#new_ch"
  post "dscs/:id/nack" => "dscs#nack"
  post "dscs/:id/ack" => "dscs#ack"
  post "dscs/:id/relay" => "dscs#relay"
  post "dscs/:id/listen" => "dscs#listen"
  post "dscs/:id/accept" => "dscs#accept"
  post "dscs/:id/cancel" => "dscs#cancel"

  #resources :users
  get "/" => "home#top"
  get "about" => "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "users/:id" => "users#show"
  get "signup" => "users#new"
  post "users" => "users#create"
  get "users/:id/edit" => "users#edit"
  post "users/:id/update" => "users#update"
  delete "users/:id" => "users#destroy"

  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
end
